### ISSUE TITLE
Shutdown Error with Java Stack

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/legacy-cli#218]
Observing a new issue when shuttting down the stack with Java client. Has been occuring for a week or two.

```
✔ Building Services
✔ Creating docker network
✔ Running Storage Service
✔ create - rest-api-cre
✔ list - rest-api-lis
✔ read - rest-api-rea
✔ Starting API Gateways
✔ Starting Entrypoints
 Function Port
 ──────── ─────
 create   45461
 list     45713
 read     42377
 Api    Port
 ────── ─────
 orders 49152
Network remove error: Error: (HTTP code 403) unexpected - error while removing network: network rest-api-net-5c2d8f54 id 4d48f3285585feeaa4c7e2d9c2505586cc0934c33b10a26287f680ce9cb86463 has active endpoints
    at /home/medgar/nitric/cli/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/home/medgar/nitric/cli/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/home/medgar/nitric/cli/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/home/medgar/nitric/cli/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: undefined,
  statusCode: 403,
  json: {
    message: 'error while removing network: network rest-api-net-5c2d8f54 id 4d48f3285585feeaa4c7e2d9c2505586cc0934c33b10a26287f680ce9cb86463 has active endpoints'
  }
}
Exiting, please wait... done
```

**Comment by tjholm** [comment]
Duplicate of #210
