### ISSUE TITLE
Cleanup error when exiting nitric run on Windows

### ISSUE THREAD

**Issue by shaf-h** [nitrictech/legacy-cli#229]
Cleanup doesn't finish, I get the following error:

`Network remove error: Error: (HTTP code 403) unexpected - error while removing network: network xxxxx-net-84cc4c51 id 0fc78374e3e01f0f3d13500c7f7582f9823ffbe0777e47299b64446c396cdff5 has active endpoints
    at C:\Users\User\AppData\Roaming\npm\node_modules\@nitric\cli\node_modules\docker-modem\lib\modem.js:324:17
    at getCause (C:\Users\User\AppData\Roaming\npm\node_modules\@nitric\cli\node_modules\docker-modem\lib\modem.js:354:7)
    at Modem.buildPayload (C:\Users\User\AppData\Roaming\npm\node_modules\@nitric\cli\node_modules\docker-modem\lib\modem.js:323:5)
    at IncomingMessage.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@nitric\cli\node_modules\docker-modem\lib\modem.js:295:14)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  reason: undefined,
  statusCode: 403,
  json: {
    message: 'error while removing network: network xxxxx-net-84cc4c51 id 0fc78374e3e01f0f3d13500c7f7582f9823ffbe0777e47299b64446c396cdff5 has active endpoints'
  }
}
Exiting, please wait... done`

**Comment by davemooreuws** [comment]
Thank you for the report.

Closing, duplicate of #210
